### ISSUE TITLE
messenger.queryUserProfile(userId)>>java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by kaonick** [messenger4j/messenger4j#102]
just try simple get userProfile got error below:
code:
`final UserProfile userProfile = messenger.queryUserProfile(userId);`
error message:
`Exception in thread "main" java.lang.IllegalArgumentException
	at java.util.Optional.orElseThrow(Unknown Source)
	at com.github.messenger4j.userprofile.UserProfileFactory.create(UserProfileFactory.java:48)
	at com.github.messenger4j.Messenger.doRequest(Messenger.java:203)
	at com.github.messenger4j.Messenger.queryUserProfile(Messenger.java:168)
	at com.ftc.bot.fb.FbPush.main(FbPush.java:46)
`
key point in UserProfileFactory.class:
`    public static UserProfile create(JsonObject jsonObject) {
        ...
        final UserProfile.Gender gender = getPropertyAsString(jsonObject, PROP_GENDER)
                .map(String::toUpperCase)
                .map(UserProfile.Gender::valueOf)
                .**orElseThrow**(IllegalArgumentException::new);
`

maybe should change orElseThorw to orElse(empty()) when data not found.

**Comment by PhantomYdn** [comment]
Can you please share message which came from FB for this user profile?

**Comment by kaonick** [comment]
Is it this?
`{"first_name":"Nick","last_name":"Kao","profile_pic":"https://platform-lookaside.fbsbx.com/platform/profilepic/?psid=2366526993387681&width=1024&ext=1538891229&hash=AeQAkNWquKengtPW","locale":"zh_TW","timezone":8,"is_payment_enabled":true,"id":"2366526993387681"}`
That's my profile.
Because there are no gender column in my profile.
