### ISSUE TITLE
Use one `Messanger` object for multiple pages

### ISSUE THREAD

**Issue by maximn** [messenger4j/messenger4j#103]
Hi,

We're working on an app that works with multiple pages ([Wix.com](url)).

We really like this library, however, it's limited to only one page.

We would like to pass the `pageAccessToken` parameter per req and not when creating the Messanger object ('Messanger.create')

Few suggestions to solve this problem-
1. `MessageResponse send(@NonNull Payload payload)` will have an optional parameter `pageAccessToken` and if it present it'll override the one from creation. 

2. Create another `Messanger` class that will work differenetly and support this functionality. There will be a common `Messanger` that stores the heavy objects (httpclient, jsonparser...) and the old `Messanger` and also the new one will both use it.

We can implement this. What do you think?

**Comment by PhantomYdn** [comment]
`Messenger` object is not heavy and does not have runtime background tasks.
So just 2 options for you:
1) Create Messenger ad hoc right at required space with known pageAccessToken
2) Use caches to store all Messengers for all required pages.

**Comment by maximn** [comment]
@PhantomYdn what do you think? Isn't creating `Gson&JsonParser` objects every time expensive? Can we do anything to make it happen?

**Comment by maximn** [comment]
Another option is to extract the code from `com.github.messenger4j.Messenger#onReceiveEvents` to another class and let me handle the HTTP and Parsing and just use the logic of the library.

**Comment by alexander-tampier** [comment]
Why don’t you just link your messenger apolication to all your pages? Why would you need more than one pageAccessToken? 
You can subscribe to more than one fb page in your application.

**Comment by maximn** [comment]
Hi, my application let my users to connect their page's messanger to my application. 
So the user can answer to messages coming to his facebook page from my app.
I have millions of users ;-)

**Comment by maxgrabenhorst** [comment]
Hi Maxim, I was off in the last weeks and month but now I'm back. I will get back to you today or tomorrow ✌️

**Comment by alexander-tampier** [comment]
@maximn - I still don’t get it because you said you only have one application or do you have more than one applications for different business needs? Then you would require more than one token

**Comment by maximn** [comment]
I have one application. It's a SAAS that let my users connect their facebook pages to my app.
Then these users can use my app to chat on facebook. And I have a lot of users.
Hope this makes it more clear.
