### ISSUE TITLE
Problem with session

### ISSUE THREAD

**Issue by amina1295** [messenger4j/messenger4j#105]
Hi! I really liked your library ! but I have some issues. I'm trying to make a chat bot that take your login password and organisation and extract information from an url but the problem is that it's always saving the last data of the last user that have made a request I tried saveral things but it's always a faillure I tried the @scope annotation, a hash map that take the sender id as a key and create a new object as a value and then when the user enter the information it affect them to the object but then I'am getting no response from the chat bot,I tried a lot of other things but I didn't get any result. can you help please.

**Comment by maxgrabenhorst** [comment]
Sorry Amina, seems to me like an app specific issue rather than a m4j bug. So please feel free to reopen when you find some specific messenger4j issue/bug.
