### ISSUE TITLE
How to get "text" payload field from MessageEchoEvent ?

### ISSUE THREAD

**Issue by thiloplanz** [messenger4j/messenger4j#110]
A MessageEchoEvent can have different types for payload fields, for example a `text` such as in

```
{
  "sender":{
    "id":"<PSID>"
  },
  "recipient":{
    "id":"<USER_ID>"
  },
  "timestamp":1457764197627,
  "message":{
    "is_echo":true,
    "app_id":1517776481860111,
    "metadata": "<DEVELOPER_DEFINED_METADATA_STRING>",
    "mid":"mid.1457764197618:41d102a3e1ae206a38",
    "text":"hello, world!"
  }
}
```

https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/message-echoes

But there does not seem to be a getter for them on `MessageEchoEvent`.

**Comment by maxgrabenhorst** [comment]
At the moment the echo event is not fully supported (and not intended to be, yet). I will investigate if it is feasible to at least make the raw JSON payload accessible.

**Comment by maxgrabenhorst** [comment]
At the moment the echo event is not fully supported (and not intended to be, yet). I will investigate if it is feasible to at least make the raw JSON payload accessible.
