### ISSUE TITLE
Query user profile deprecated fields

### ISSUE THREAD

**Issue by arjo14** [messenger4j/messenger4j#111]
(#100) **The last_ad_referral** and **is_payment_enabled** fields are now **deprecated**. Please refer to our Developer Document for more info., type=Optional[OAuthException], code=Optional[100], fbTraceId=Optional[BALnJ3YdOrl])

**Comment by AlonKapi** [comment]
Check:
https://developers.facebook.com/docs/messenger-platform/identity/user-profile/

You can easily get the profile data yourself, until they fix this.

**Comment by maxgrabenhorst** [comment]
Fix with #114
