### ISSUE TITLE
Sending facebook/youtube video with preview

### ISSUE THREAD

**Issue by AlonKapi** [messenger4j/messenger4j#112]
Hi,
I want the bot to send facebook/youtube videos with the preview (and any other link actually),
I tried to use a TextMessage format but it just sends the link without preview, I also tried to send it as a video attachment but I'm getting an exception that messenger4j can't grab the file.

According to Facebook send API reference here:
https://developers.facebook.com/docs/messenger-platform/reference/send-api/#attachment

Only attachment objects can preview the link, so how can I accomplish that using messenger4j?

**Comment by syedaffanhamdani** [comment]
Hi, I am having the same issue. Were you able to solve it?

**Comment by AlonKapi** [comment]
Hi, yes I've..

I used:
`final OpenGraphObject openGraphObject = OpenGraphObject.create(new URL(message.getValue()), Optional.empty());
List<OpenGraphObject> list = new ArrayList<OpenGraphObject>();
list.add(openGraphObject);
final OpenGraphTemplate openGraphTemplate = OpenGraphTemplate.create(list);
MessagePayload payload = MessagePayload.create(senderId, MessagingType.RESPONSE,TemplateMessage.create(openGraphTemplate));`

Where message.getValue() is the user input as a string.

**Comment by maxgrabenhorst** [comment]
Resolved, therefore close.
