### ISSUE TITLE
Testing: Make com.github.messenger4j.Messenger None-Final

### ISSUE THREAD

**Issue by hannes-angst** [messenger4j/messenger4j#113]
We use Mockito to mock responses from the Messenger class.

However, in JUnit4 it is not possible to spy on a final class.

    @Test
    public void send_text_message_with_image_and_title() throws Exception {
        Messenger messengerClient = mock(Messenger.class);
      

        when(messengerClient.send(any())).then(invocation ->
                {
                    Payload payload = invocation.getArgument(0);
                    assertNotNull(payload);
                    return -- some response--;
                }
        );

        ChatResponse response = ChatResponse.builder()
                --snip--
                .build();

        messageService.sendResponse(response, recipientId);

        verify(messengerClient).send(-- some response--);
        verify(messengerClient).send(-- some response--);
        verify(messengerClient).send(-- some response--);
    }

**Comment by maxgrabenhorst** [comment]
Hi @hannes-angst,
actually Mockito is able to mock final classes. Therefore you have to use the inline mock maker.
Please see for more details: https://www.baeldung.com/mockito-final

If there are any issues please feel free to reopen this issue. Thanks.
