### ISSUE TITLE
MessengerApiException when calling messenger.queryUserProfile(senderId);

### ISSUE THREAD

**Issue by fjfo** [messenger4j/messenger4j#115]
hi,

I got these bug when calling:

" final UserProfile userProfile = this.messenger.queryUserProfile(senderId);"

MessengerApiException(super=com.github.messenger4j.exception.MessengerApiException: (#100) The last_ad_referral and is_payment_enabled fields are now deprecated. Please refer to our Developer Document for more info., type=Optional[OAuthException], code=Optional[100], fbTraceId=Optional[GbgQFPxoD11])
	at com.github.messenger4j.exception.MessengerApiExceptionFactory.create(MessengerApiExceptionFactory.java:29)

What is that mean? How to get over it?

**Comment by fjfo** [comment]
4 days gone with no reply.
Please help me

**Comment by NibinIssac** [comment]
This issue is explained in #114 . I faced similar issue and fixed it by taking  latest cut and modify the code and build jar file. Not sure if admin is planning another release to fix this issue.

**Comment by fjfo** [comment]
Thanks @NibinIssac . Appreciate it!

**Comment by zwaldeck** [comment]
At the moment you can override the method and change the query string, but you will need to use reflections to access doRequest method in the Messenger class.

I'm doing this now, just so the refactoring work is minimal when an update to the library comes

**Comment by zwaldeck** [comment]
@maxgrabenhorst Maybe it's good to do a bugfix release on this issue, as it breaks a core functionality?

**Comment by maxgrabenhorst** [comment]
I will do a bugfix release within the next days.

**Comment by maxgrabenhorst** [comment]
Close due to duplicate. Issue already resolved in develop branch. As stated above bug release follows soon.

**Comment by maxgrabenhorst** [comment]
messenger4j 1.1.0 is out!
