### ISSUE TITLE
Support for Payments

### ISSUE THREAD

**Issue by akinmail** [messenger4j/messenger4j#17]
Hello, thanks for this library, I know that facebook messenger payments is still in beta i will just like to know if there's any plan to add Buy button implementation. Can i maybe make a pull request?

**Comment by maxgrabenhorst** [comment]
Hi, thanks for using messenger4j! As you said payment support is still in beta but messenger4j will support it in near future. Currently I do a bigger redesign and reimplementation including full jdk8 support. When this is finished I will implement payment functionality.
