### ISSUE TITLE
The ListTeplate Large Element Type has not effect

### ISSUE THREAD

**Issue by menwn** [messenger4j/messenger4j#18]
The list rendered on FB is always the same no matter if I use `ListTemplate.newBuilder(ListTemplate.TopElementStyle.LARGE)` or `ListTemplate.newBuilder(ListTemplate.TopElementStyle.COMPACT)`

`ListTemplate.newBuilder(ListTemplate.TopElementStyle.LARGE)
                 .addElements()
                    .addElement("title1")
                    .subtitle("subTitle1")
                    .imageUrl("http://example.com/1.png")
                    .buttons(Button.newListBuilder().addUrlButton("t1", "http://example.com/1").toList().build())
                .toList()
                    .addElement("title2")
                    .subtitle("subTitle2")
                    .imageUrl("http://example.com/2.png")
                    .buttons(Button.newListBuilder().addUrlButton("t2", "http://example.com/2").toList().build())
                .toList()
                .done()
                .build();`

I cannot figure out if this is a problem with the library or with FB though because the json this sends is:

`{
   "recipient":{
      "id":"1928466753845863"
   },
   "message":{
      "attachment":{
         "type":"template",
         "payload":{
            "top_element_style":"large",
            "elements":[
               {
                  "title":"title1",
                  "subtitle":"subTitle1",
                  "image_url":"http://example.com/1.png",
                  "buttons":[
                     {
                        "url":"http://example.com/1",
                        "title":"t1",
                        "type":"web_url"
                     }
                  ]
               },
               {
                  "title":"title2",
                  "subtitle":"subTitle2",
                  "image_url":"http://example.com/2.png",
                  "buttons":[
                     {
                        "url":"http://example.com/2",
                        "title":"t2",
                        "type":"web_url"
                     }
                  ]
               }
            ],
            "template_type":"list"
         }
      }
   }
}`

which seems correct to me. It is like the ** "top_element_style":"large"** is treated like COMPACT.

**Comment by maxgrabenhorst** [comment]
Hi, thanks for reporting this issue.
I checked the FB documentation and it seems that the JSON is still right. There were no API changes. Also "large" is the default if there is no "top_element_style" specified.
According the docs "top_element_style is always rendered as compact style on web right now". So please make sure that you use the Messenger mobile App to verify the behavior.
If it still doesn't work please file a bug here: https://developers.facebook.com/bugs/

**Comment by maxgrabenhorst** [comment]
@menwn does this behavior still occur? Otherwise I would close this issue.

**Comment by menwn** [comment]
@maxgrabenhorst I did not have the opportunity to test again. I will try to do it over the weekend and let you know.

**Comment by maxgrabenhorst** [comment]
Close this issue now. Please reopen if still relevant.
