### ISSUE TITLE
How to run more than one Bot from the same App

### ISSUE THREAD

**Issue by chachoe** [messenger4j/messenger4j#19]
Hi! Im trying to run more than one bot from the same App because we use a lot of the same prcedures and I can use a common core. 
I can make a MessengerPlatformCallbackHandler for each bot.
But i don´t have idea how to mannage two diferents senders.. 
Excuse me if im asking a simple question but it would be very helpfull for me

This is the structure of my project where I separate the Handler from the Sender, that´s in the Service
![image](https://user-images.githubusercontent.com/2281074/26842890-b7523ae6-4ac4-11e7-8148-e991eb455763.png)

And this is how I use the sender

![image](https://user-images.githubusercontent.com/2281074/26843058-535c2f8c-4ac5-11e7-9dc7-72bf6a06c2c3.png)

**Comment by maxgrabenhorst** [comment]
Hi, every question is very welcome :)
If you really want to run more than one bot from the same application (consider scalability, reliability, monitoring...)  you could just instantiate the `MessengerSendClient` in the `FBServiceImpl` constructor (if this service is not shared). If this service is shared you could instantiate the `MessengerSendClient` in the constructor of the `MessengerPlatformCallbackHandler` and pass it as argument to a service method like `FBService#sendTextMessage(MessengerSendClient bot, String text, List<QuickReply> botones)`.
If the different `MessengerSendClient`s should be injectable you could use [Qualifiers](http://zetcode.com/articles/springbootqualifier/).

Hope this helps. If you have further questions please feel free to ask.

**Comment by maxgrabenhorst** [comment]
@chachoe Do you need any further help regarding this issue? Otherwise I would close it.

**Comment by chachoe** [comment]
@maxgrabenhorst sorry for the long time without answering, I were on holidays :)

Unfortunatly, i´m having many problems because when I add another _MessengerPlatformCallbackHandler_ Im not receivign anything in the app. 
![image](https://user-images.githubusercontent.com/2281074/27641138-684de47a-5bf1-11e7-8c59-2caa6efe38bc.png)

For the senders I decided to instantiate the MessengerSendClient in the CallbackHandler and pass it as argument to the services. This is the wat I´m doing it, but probably also its wrong. 
![image](https://user-images.githubusercontent.com/2281074/27641539-8c6c2050-5bf2-11e7-8707-aa238730626a.png)

I will keep working on it and any progress I make I wil notify you!

**Comment by chachoe** [comment]
@maxgrabenhorst i just resolved it ! i was forgeting to put wich page i wanted to redirect the messages in the Facebook Configuration! Very stupíd! 

Thanks a lot!

Close the issue :+1:

**Comment by maxgrabenhorst** [comment]
Happy to hear that you have solved your problem :)
