### ISSUE TITLE
Messenger update

### ISSUE THREAD

**Issue by wmalgarizi** [messenger4j/messenger4j#21]
Will the graph api update affect the lib?

**Comment by maxgrabenhorst** [comment]
Hi,
currently messenger4j misses some new features of the Messenger Platform.
In addition not all changes introduced in the latest Messenger Platform updates are adopted yet.
I'm currently very busy (wedding preparation, ...) but there will be a big update to messenger4j in August / September fully supporting the Messenger Platform V2.0, full Java 8 support, etc.

**Comment by wmalgarizi** [comment]
Nice.. Thanks for listening and congratulations for the wedding..

**Comment by jsom** [comment]
Hey @maxgrabenhorst -- any update on Platform V2 support? Is there a branch that others could contribute to?

**Comment by maxgrabenhorst** [comment]
Hey @jsom,
currently I'm working hard on the new messenger4j version and Platform V2 support.
I plan to release it by the end of this month. 
After the release there will be a contribution branch. At the moment there are too much changes.

**Comment by maxgrabenhorst** [comment]
Hi all,
messenger4j 1.0.0-M1 is out. This is a complete rewrite of the library to make it even better.
From now on it's quite easier to extend the functionality. Please try it out and provide feedback. 
The missing features are already planned to be implement in the short term.
