### ISSUE TITLE
Send text messages with links and previews

### ISSUE THREAD

**Issue by chachoe** [messenger4j/messenger4j#22]
I´m using the function 
 `MessengerResponse sendTextMessage()` 
for sending dinamics messages in my bot. Some times the bot send an url to another page. 
The problem I have is that i want that the message that arrives to the receiver don´t load a preview to the link as usal. 

For example the text I want to send is: 
"This is amazing! 
http://edition.cnn.com/2017/07/14/health/why-countries-are-obese-culture-exercise-diet/index.html"

And I expect the reciver can visualize it in this way:
![image](https://user-images.githubusercontent.com/2281074/28215144-512b28b8-6883-11e7-9885-14944dcd36ab.png)

But when the bot send that message the reciver visualize this:
![image](https://user-images.githubusercontent.com/2281074/28215232-a00f4374-6883-11e7-8b35-71c692a3f5bb.png)

Is there a way to send messages with links and the reciver can watch the preview?

Thanks!

**Comment by maxgrabenhorst** [comment]
As far as I know this is not possible or at least it is not possible to specify if a preview should be rendered or not. But I will investigate it further for you.

**Comment by chachoe** [comment]
Thanks max!

**Comment by maxgrabenhorst** [comment]
Haven't found any information regarding your question so far. Is this still relevant? I recommend that you create feature request on facebook directly.
