### ISSUE TITLE
image_aspect_ratio for generic template

### ISSUE THREAD

**Issue by johanvs** [messenger4j/messenger4j#24]
Hello,
Is it possible to implement the `image_aspect_ratio` parameter for the generic template?
It is documented [here](https://developers.facebook.com/docs/messenger-platform/send-api-reference/generic-template)
Thanks,

**Comment by maxgrabenhorst** [comment]
Hi,
will be part of the next release

**Comment by maxgrabenhorst** [comment]
messenger4j 1.0.0-M1 now supports also the image_aspect_ratio :)
