### ISSUE TITLE
support for sticker?

### ISSUE THREAD

**Issue by dandirusli** [messenger4j/messenger4j#27]
any plan to support sticker_id?

**Comment by maxgrabenhorst** [comment]
I haven't found any information regarding sticker_id in the messenger platform documentation. 
Do you have a hint for me?

**Comment by maxgrabenhorst** [comment]
I close this issue. Please reopen if still relevant.

**Comment by Plotron** [comment]
It's a funny thing. Apparently, the sticker id would be the most reliable way of checking whether the user sent a like or something else. More information can be found here **(#12)**: https://chatbotsmagazine.com/listicle-of-things-missing-from-facebook-messenger-chatbot-platforms-documentation-d1d50922ef15
I found it by accident when I was troubleshooting my own bot. Here's the payload I got when I sent a 'like' to my bot.

payload: {"object":"page","entry":[{"id":"2061796340715698","time":1511202753347,"messaging":[{"sender":{"id":"~~XXXXX~~"},"recipient":{"id":"2061796340715698"},"timestamp":1511202752806,"message":{"mid":"mid.$cAAcJxRG2E_FmC_lRJlf2rP1kC830","seq":557726,"sticker_id":369239343222814,"attachments":[{"type":"image","payload":{"url":"https:\/\/scontent.xx.fbcdn.net\/v\/t39.1997-6\/p100x100\/851587_369239346556147_162929011_n.png?_nc_ad=z-m&_nc_cid=0&oh=2900b989c309176be137033bd9a8856e&oe=5AA49CB0","**sticker_id":369239343222814**}}]}}]}]} | signature: sha1=0cc233c561f95a60ec9aca24f515b6d064cf644c
