### ISSUE TITLE
Date picker card

### ISSUE THREAD

**Issue by SubNader** [messenger4j/messenger4j#28]
Hello,

I was just wondering if there are any existing (or planned) extensions that facilitates date picking?
If not, what would be the best approach to build one?

Thanks,
Nader

**Comment by maxgrabenhorst** [comment]
Hi,
I've not found any documentation about a date picker.
Did I miss something? Or do you have a hint for me?

Parsing the user input is not suitable?

**Comment by maxgrabenhorst** [comment]
Still relevant? Otherwise I would close that issue.

**Comment by maxgrabenhorst** [comment]
I close this issue. Please reopen if still relevant.
