### ISSUE TITLE
Support for submenus

### ISSUE THREAD

**Issue by johanvs** [messenger4j/messenger4j#31]
Is it possible to add submenus items in persistent menu ?
[https://developers.facebook.com/docs/messenger-platform/reference/messenger-profile-api/persistent-menu](url)
Thanks,

**Comment by maxgrabenhorst** [comment]
Will be part of next release.
Thanks for using messenger4j.

**Comment by maxgrabenhorst** [comment]
Messenger4j 1.0.0-M1 is out. Submenus are now supported.

**Comment by johanvs** [comment]
Thanks a lot !
