### ISSUE TITLE
Text Limit updated

### ISSUE THREAD

**Issue by johanvs** [messenger4j/messenger4j#32]
The text limit is 640, and not 320.
(the constant TEXT_CHARACTER_LIMIT in your code)
[https://developers.facebook.com/docs/messenger-platform/send-api-reference/text-message](url)

**Comment by maxgrabenhorst** [comment]
Will be fixed with the next release.

**Comment by maxgrabenhorst** [comment]
Messenger4j 1.0.0-M1 is out. Your issue is now fixed.
