### ISSUE TITLE
About open-graph & media template

### ISSUE THREAD

**Issue by uugan** [messenger4j/messenger4j#35]
Please add open-graph & media template. This template can send third party's video, music url (spotify, youtube, facebook page videos etc).
In our library sendVideoAttachment sends mp4 files only.
https://developers.facebook.com/docs/messenger-platform/send-messages/template/open-graph
https://developers.facebook.com/docs/messenger-platform/send-messages/template/media

**Comment by uugan** [comment]
0.8.0 vs 1.0.0-M1 huge difference in coding. 
Why did you delete all previous version methods?

**Comment by maxgrabenhorst** [comment]
Version `1.0.0-M2` now supports the Open Graph Template. The media template will be part of the next milestone release along with the attachment upload api.
