### ISSUE TITLE
IllegalArgumentException after sending a SenderActionPayload

### ISSUE THREAD

**Issue by gKatsu** [messenger4j/messenger4j#36]
Hi,
I am using messenger4j API to build a chatbot.
After the upgrade from 0.8.0 to 1.0.0-M1 I get an error after sending a SenderActionPayload.

My code is as following:
`
this.messenger.send( SenderActionPayload.create(userInfo.getUserId(),SenderAction.TYPING_ON));
`
This request throws an IllegalArgumentException :

`java.lang.IllegalArgumentException: null
	at java.util.Optional.orElseThrow(Optional.java:290) ~[na:1.8.0_152]
	at com.github.messenger4j.send.MessageResponseFactory.create(MessageResponseFactory.java:24) ~[messenger4j-1.0.0-M1.jar:na]
	at com.github.messenger4j.Messenger.doRequest(Messenger.java:203) ~[messenger4j-1.0.0-M1.jar:na]
	at com.github.messenger4j.Messenger.send(Messenger.java:120) ~[messenger4j-1.0.0-M1.jar:na]`

Thanks

**Comment by maxgrabenhorst** [comment]
Hi, thanks for reporting this bug.
I will investigate it later and try to release a bugfix version tomorrow.
Any other issues while migrating to the new version?
Or any other feedback?

Thanks
Max

**Comment by gKatsu** [comment]
Thanks Max for looking into this issue.
No other issues so far after the migration. I find the new API better and easiest to use.
The only thing I think is missing, and it will be good to add it to MessengerSettings is [domain-whitelisting](https://developers.facebook.com/docs/messenger-platform/thread-settings/domain-whitelisting/)
Thanks

**Comment by maxgrabenhorst** [comment]
Thanks for your (positive) feedback! 
I've released `1.0.0-M2`. Should be synced with Maven Central within the next minutes.
Now your reported bug is fixed and I added support for domain whitelisting.

Hope you like it.
Max

**Comment by gKatsu** [comment]
Thanks a lot for the quick fix and the domain whitelisting support.
