### ISSUE TITLE
Attaching from file

### ISSUE THREAD

**Issue by uugan** [messenger4j/messenger4j#38]
How to send file (image) from local folder?
https://developers.facebook.com/docs/messenger-platform/send-messages
>curl  \
  -F 'recipient={"id":"<PSID>"}' \
  -F 'message={"attachment":{"type":"<ASSET_TYPE>", "payload":{"is_reusable"=true}}}' \
  -F 'filedata=@/tmp/shirt.png;type=image/png' \
  "https://graph.facebook.com/v2.6/me/messages?access_token=<PAGE_ACCESS_TOKEN>"

Does UrlRichMediaAsset can do that?

**Comment by maxgrabenhorst** [comment]
Also relevant for implementation:
https://developers.facebook.com/docs/messenger-platform/send-messages/saving-assets
