### ISSUE TITLE
All Event classes should be public

### ISSUE THREAD

**Issue by jzarnikov** [messenger4j/messenger4j#4]
Following classes:
```
com.github.messenger4j.receive.events.TimestampedEvent, 
com.github.messenger4j.receive.events.MessageEvent, 
com.github.messenger4j.receive.events.CommonTextMessageEvent
```
are package private. This is a problem - for example if you want to create a logging-service that logs each incoming message (regardless of the type). It's not possible to define a method that accepts all types of messages:
```
public void logEvent(TimestampedEvent event) {
    LOG.info("event: {}", event);
}
```
Because TimestampedEvent is not public.

**Comment by maxgrabenhorst** [comment]
The abstract superclass  `com.github.messenger4j.receive.events.Event` is public. You can use this class to define a method that accepts all types of messages. I see no use case where you would use the classes TimestampedEvent, MessageEvent, and CommonTextMessageEvent directly.

Does this help?

**Comment by maxgrabenhorst** [comment]
As discussed via Email there is no use-case that requires making these classes public.
To define a method that accepts all types of messages the `Event` class can be used. The event classes get a public constructor, hence there is no need to mock these classes.
