### ISSUE TITLE
Handover Protocol Support

### ISSUE THREAD

**Issue by maxgrabenhorst** [messenger4j/messenger4j#41]
Add support for:
https://developers.facebook.com/docs/messenger-platform/handover-protocol

**Comment by alexander-tampier** [comment]
UC1 - support for Passing Thread Control to facebook inbox when a user confirm that he wants to talk with a human. Related to the passing control receiving standby webhook events should be supported as well. 
https://developers.facebook.com/docs/messenger-platform/handover-protocol/pass-thread-control
UC2 - support for Take Thread Control when the Primary Receiver (Bot) wants the control back:
https://developers.facebook.com/docs/messenger-platform/handover-protocol/take-thread-control
UC3 - support for Request Thread Control when the Secondary Receiver notifies the Primary that it wants control
https://developers.facebook.com/docs/messenger-platform/handover-protocol/request-thread-control
