### ISSUE TITLE
Checkbox Plugin Support

### ISSUE THREAD

**Issue by maxgrabenhorst** [messenger4j/messenger4j#49]
Add support for:
https://developers.facebook.com/docs/messenger-platform/discovery/checkbox-plugin

Especially `user_ref` property needs to be handled properly.

**Comment by jjtindale** [comment]
Hi @maxgrabenhorst, first thing: this library is awesome. It's really well written and easy to understand. Thanks for your efforts 👍 

I needed to integrate the Checkbox Plugin and I wanted to use messenger4j even though the support isn't 100% there yet, so I forked, branched and implemented it. It's here https://github.com/messenger4j/messenger4j/pull/58. 

Let me know what you think and feel free to use as much or as little as you like.

**Comment by maxgrabenhorst** [comment]
Today released as part of v1.0.0-M3
