### ISSUE TITLE
Account Linking Endpoint Support

### ISSUE THREAD

**Issue by maxgrabenhorst** [messenger4j/messenger4j#54]
Add support for account linking endpoints:
https://developers.facebook.com/docs/messenger-platform/identity/account-linking

**Comment by akinmail** [comment]
Hey, do you need help with this?

**Comment by maxgrabenhorst** [comment]
Hi, thanks for offering your help!
There are some things that have to be done in advance but I will come back to you if this feature is ready to be implemented :)

**Comment by n0mer** [comment]
@maxgrabenhorst hi Max, any update on this? Maybe you might use @akinmail help :) ?
