### ISSUE TITLE
Ability to resend a previous message. 

### ISSUE THREAD

**Issue by akinmail** [messenger4j/messenger4j#57]
I would like to resend a message i have previously sent to the user, instead of saving data about the message in db and then regenerating the message template again. is there another way of saving a template with data(previous message).

Thanks

**Comment by maxgrabenhorst** [comment]
Hi, 
I understand your requirement but this is nothing that will be handled by the library itself.
Basically the library is designed as an API wrapper. The ability to resend previous messages is more application specific and has to be handled by the application itself. This is also true for retry strategies, rate limiting and so on.

But the new API design introduced in version 1.0.0-M1 should make reusing previous messages much easier. If there is a limited amount of messages which should be reused you can easily create them once and store them in memory, e.g. in a `MessageStoreService`.

If you need further assistance here please come back with more information about your use-case. I'm happy to help.

**Comment by maxgrabenhorst** [comment]
I will close this issue. If you have any question please reopen.
