### ISSUE TITLE
Support for messenger_extensions

### ISSUE THREAD

**Issue by anshchauhan** [messenger4j/messenger4j#6]
Hi,

Thank you for the great library. It has made my life so easy. 

I wanted to know that do you have messenger_extensions support as stated here?
https://developers.facebook.com/docs/messenger-platform/messenger-extension

**Comment by maxgrabenhorst** [comment]
Hi,
sorry for the late reply. I'm back from holidays now (spent a few days in India 👍 ).

Currently messenger4j does not support the messenger_extensions feature. But it is already planned to be implemented.
I will prioritize it so it will be part of the next release (released in probably 2 weeks).

**Comment by maxgrabenhorst** [comment]
@anshchauhan messenger4j 0.8.0 with messenger extensions support is now released.
In order to enable messenger extensions with your URL Button, you have to do the following:
```java
List<Button> buttons = Button.newListBuilder()
                .addUrlButton("Show Website", "https://petersapparel.parseapp.com")
                    .webviewHeightRatio(WebviewHeightRatio.FULL)
                    .messengerExtensions(true)
                    .fallbackUrl("https://petersfancyapparel.com/fallback")
                    .toList()
                .build();
```

It is also supported for CallToActions (Persistent Menu) and DefaultAction (List Template).

**Comment by chachoe** [comment]
Excuse me, I don´t understand how to set de Persisten Menu... Can you give us an example to implementate it? Where can we implementate it, in wich part of the code?

**Comment by maxgrabenhorst** [comment]
Hi,
the FB Persistent Menu API has changed but the old API is still supported.
Support for the new API is part of the next messenger4j release.
When using the old API you can set the Persistent Menu as follows:
```
final CallToAction firstMenuItem = CallToAction.newBuilder()
                .type(POSTBACK)
                .title("Help")
                .payload("DEVELOPER_DEFINED_PAYLOAD_FOR_HELP")
                .build();

        final CallToAction secondMenuItem = CallToAction.newBuilder()
                .type(POSTBACK)
                .title("Start a New Order")
                .payload("DEVELOPER_DEFINED_PAYLOAD_FOR_START_ORDER")
                .build();

        final CallToAction thirdMenuItem = CallToAction.newBuilder()
                .type(WEB_URL)
                .title("Checkout")
                .url(new URL("http://petersapparel.parseapp.com/checkout"))
                .webviewHeightRatio(WebviewHeightRatio.COMPACT)
                .messengerExtensions(true)
                .fallbackUrl(new URL("https://peterssendreceiveapp.ngrok.io/fallback"))
                .build();

        final CallToAction fourthMenuItem = CallToAction.newBuilder()
                .type(WEB_URL)
                .title("View Website")
                .url(new URL("http://petersapparel.parseapp.com/"))
                .build();

        final List<CallToAction> menuItems = new ArrayList<>(Arrays.asList(firstMenuItem, secondMenuItem, thirdMenuItem, fourthMenuItem));

        MessengerSetupClient messengerSetupClient = MessengerPlatform.newSetupClientBuilder(PAGE_ACCESS_TOKEN)
                .build();
        messengerSetupClient.setupPersistentMenu(menuItems);
```
For more examples take a look at `MessengerSetupClientTest`.
In the future please open a new issue for your question since your question is not related to this issue. Thanks.
