### ISSUE TITLE
Typing off is not working

### ISSUE THREAD

**Issue by uugan** [messenger4j/messenger4j#61]
SenderAction senderAction = SenderAction.TYPING_OFF;
   SenderActionPayload payload = SenderActionPayload.create(recipientId, senderAction);
   MessageResponse res =  messenger.send(payload);

Please check this. It's gives response but typing ... is still exists.

**Comment by uugan** [comment]
Oh it's a bug. but still not fixed (20171206)
reported on October 15th: https://developers.facebook.com/bugs/128476284591188/

**Comment by maxgrabenhorst** [comment]
thanks for reporting the bug. i will close this issue since it's a FB bug.
