### ISSUE TITLE
Breaking changes in facebook messenger API from Feb 2018

### ISSUE THREAD

**Issue by NibinIssac** [messenger4j/messenger4j#62]
Hi 
I am using messenger4j 0.8.0 in production i have not yet moved to new release because application is already in production . Just read in facebook documentation about 

Breaking Change Notice
Effective February 19, 2018, the Send API will no longer include recipient_id in the response for message sends that use recipient.user_ref or recipient.phone_number to identify the message recipient.

Please let me know how this will be implemented in messenger4j.

**Comment by maxgrabenhorst** [comment]
Hi, these changes will be part of the 1.0.0-M3 release which is scheduled for end of this year.
After February 19, 2018 messenger4j 0.8.0 will not work anymore.
