### ISSUE TITLE
Issue with messenger4j when user sent Wave message to chatbot

### ISSUE THREAD

**Issue by NibinIssac** [messenger4j/messenger4j#63]
I faced a issue yesterday when user sent a wave message to chatbot . it came as a attachment with type as payload. library failed to process message because payload type is not mentioned .  I have included the exact message that is received

 [/ChatBot] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: No enum constant com.github.messenger4j.receive.events.AttachmentMessageEvent.AttachmentType.FALLBACK] with root cause
 java.lang.IllegalArgumentException: No enum constant com.github.messenger4j.receive.events.AttachmentMessageEvent.AttachmentType.FALLBACK
        at java.lang.Enum.valueOf(Enum.java:238)
        at com.github.messenger4j.receive.events.AttachmentMessageEvent$AttachmentType.valueOf(AttachmentMessageEvent.java:177)
        at com.github.messenger4j.receive.events.AttachmentMessageEvent$Attachment.fromJson(AttachmentMessageEvent.java:120)

Received Messenger Platform callback - payload: {"object":"page","entry":[{"id":"","time":1512800331017,"messaging":[{"sender":{"id":""},"recipient":{"id":""},"timestamp":1512800330767,"message":{"mid":"mid.$cAAIvdsUfEzVmazJsD1gOe0X-txIw","seq":9090,"attachments":[{"title":"Julie is waving at you!","url":null,"type":"fallback","payload":null}]}}]}]}| signature: {}sha1=2c15651a671ece936e39967491285e3d047f167c

**Comment by maxgrabenhorst** [comment]
This is a known bug in versions prior to version 1.0.0-M1. With version 1.0.0-M1 this issue is fixed.
