### ISSUE TITLE
get/set methods vs direct

### ISSUE THREAD

**Issue by PhantomYdn** [messenger4j/messenger4j#64]
Hello,

Prior to 1.0.0 code had normal getters and setters. For example: 

```java
public List<Attachment> getAttachments() {
        return attachments;
    }
```

But that was refactored towards:

```java
public List<Attachment> attachments() {
        return attachments;
    }
```

Unfortunately, this refactoring is pretty inconvinient, because objects can't be treated as beans and can't be used in javascript and other scripting languages in convinient way, like `event.attachments`.

Any possibility to revert that back?

**Comment by maxgrabenhorst** [comment]
Hi, thanks for your feedback. I will consider to revert that back in an upcoming version.
