### ISSUE TITLE
Question about FallbackAttachment

### ISSUE THREAD

**Issue by jorgealfonsogarcia** [messenger4j/messenger4j#65]
I have the following question:

Why does FallbackAttachment return the plain JSON and not an object that represents the attached information?

Best regards, and congratulations for the new version of the library. It has been a great improvement and it is very useful.

**Comment by maxgrabenhorst** [comment]
Hi Jorge, thanks you.
The reason for returning the plain JSON instead of an object is the lack of documentation.
If have not found a reliable description of the shape of the fallback attachment.
Hence to be as compatible as possible I decided to return the plain JSON.

Best regards
Max

**Comment by maxgrabenhorst** [comment]
I close this issue. Feel free to reopen if you have more question or if we should discuss it in more detail.
