### ISSUE TITLE
Exception if click "test" button infacebook dev console

### ISSUE THREAD

**Issue by PhantomYdn** [messenger4j/messenger4j#67]
There is "test" button in facebook dev console. After clicking the following exception is rised:

```java
[RROR] (2017-12-22 20:48:53,683) DefaultExceptionMapper: Unexpected error occurred
java.lang.IllegalArgumentException
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.github.messenger4j.Messenger.onReceiveEvents(Messenger.java:148)

```

**Comment by maxgrabenhorst** [comment]
I don't know the button but I guess that this sends a Graph API request which has a different shape than the common Messenger Platform request. Therefore I close this issue. If you need further assistance please provide the request JSON which is processed by messenger4j.

**Comment by hakkinepally** [comment]
Apparently even in the latest code 1.0.0-M3, Looks like there is an issue in the code.

1. When value = messaging,
payload: {"object":"page","entry":[{"id":"166110103928013","time":1519274875684,"messaging":[{"recipient":{"id":"166110103928013"},"timestamp":1519274875684,"sender":{"id":"1530111443773319"},"postback":{"payload":"Get Started","title":"Get Started"}}]}]}
2. Sometimes the value = standby,
payload: {"object":"page","entry":[{"id":"166110103928013","time":1519274875684,"standby":[{"recipient":{"id":"166110103928013"},"timestamp":1519274875684,"sender":{"id":"1530111443773319"},"postback":{"title":"Get Started"}}]}]}
