### ISSUE TITLE
verifyWebhook()

### ISSUE THREAD

**Issue by kill4food** [messenger4j/messenger4j#69]
Hi,

I didn't understand how exactly should i use this function.
My java program isn't sending the response itself, but sending it to another webhook that sends a response to FB.

So how should verifyWebhook() should tell me true/false if the input was correct?

**Comment by maxgrabenhorst** [comment]
Hi,
this is just a helper function.
When you setup your messenger bot on FB you have to provide the actual URL of your bot / implementation. To ensure that just you can use your bot FB issues a GET request and expects a specific response. The `verifyWebhook` methods just supports this process. For more information please refer to: https://developers.facebook.com/docs/messenger-platform/getting-started/webhook-setup
After the setup is finished you don't need this method anymore.

**Comment by lobo922** [comment]
I know it’s purpose, but I don’t understand how to use it and what it returns
Can I have an example how to use it?

**Comment by maxgrabenhorst** [comment]
Ah okay. Yes of course. Take a look here:
https://github.com/messenger4j/messenger4j-spring-boot-quickstart-template/blob/integration_m4j_1_0_0/src/main/java/com/github/messenger4j/quickstart/boot/MessengerPlatformCallbackHandler.java

Line 95

Feel free to ask if you have more questions.
