### ISSUE TITLE
Invalid template type

### ISSUE THREAD

**Issue by nomanbiniqbal** [messenger4j/messenger4j#7]
when i use button type then its returning me invalid button type.

**Comment by maxgrabenhorst** [comment]
Thanks for reporting this bug. Can you please provide more information? Example code would be great.

**Comment by maxgrabenhorst** [comment]
@nomanbiniqbal does this error still occur?

**Comment by nomanbiniqbal** [comment]
Thanks for your replay but the couse of this issue was on my application end .
I was using old version for gson after i update that its work fine.

By the way thanks for your reply :) love u
