### ISSUE TITLE
Please provide release date for  1.0.0-M3 version

### ISSUE THREAD

**Issue by NibinIssac** [messenger4j/messenger4j#71]
Hi,

I have earlier asked a question about breaking changes in facebook which will be effective by February 19, 2018 . [issue 62](https://github.com/messenger4j/messenger4j/issues/62)

Please provide when we can expect this version

Thanks
Nibin

**Comment by maxgrabenhorst** [comment]
Hi Nibin,

M3 will be released this weekend. All announced breaking changes are taken into account so that M3 will work after February 19, 2018.

Best
Max

**Comment by maxgrabenhorst** [comment]
Hi @NibinIssac, 1.0.0-M3 was just released
