### ISSUE TITLE
Getting  Entry id (page)

### ISSUE THREAD

**Issue by kill4food** [messenger4j/messenger4j#75]
Is it there a way to get the page id from the entry? entry[0].id

**Comment by maxgrabenhorst** [comment]
For which use case do you need it? You can obtain the page id from event.recipient.id. Does this work or is there a use case where you either don't have a recipient or the id is unequal entry[0].id?

**Comment by kill4food** [comment]
The use case case is that i want my application to serve different pages so I need to use that page ID to insert it to my DB
I will try to use your suggestion and update if there is a problem with it
Thanks

**Comment by maxgrabenhorst** [comment]
Okay understand. Please give feedback if you have any limitations when using my suggestion.

**Comment by maxgrabenhorst** [comment]
I assume that the solution worked and close the issue. Feel free to reopen if you still need help on this topic.
