### ISSUE TITLE
Getting this error while sending message 

### ISSUE THREAD

**Issue by nibinki** [messenger4j/messenger4j#80]
Hi,

I got this error yesterday when trying to send message .

MessengerApiException(super=com.github.messenger4j.exception.MessengerApiException: (#2) Service temporarily unavailable, type=Optional[OAuthException], code=Optional[2], fbTraceId=Optional[DRK+4tBKnaY]).

i was trying to fetch the user profile

UserProfile userProfile = null;
			try {
				//userProfile = messenger.queryUserProfile(senderId);
			} catch (MessengerApiException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			} catch (MessengerIOException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}

**Comment by cptstffn** [comment]
Seems like you have a conflict with your data (Old or outdated?). 
maybe just clean your cache and give it a second try. Or maybe the ist just temporarily unreachable due down time.

**Comment by maxgrabenhorst** [comment]
Do you still have this issue? Seems to me that there was an error on the messenger platform side.

**Comment by nibinki** [comment]
Issue was with platform today I am not receiving this error.  Thanks for your time.
