### ISSUE TITLE
Support for thumbs up and thumps down as feedback  for messages

### ISSUE THREAD

**Issue by nibinki** [messenger4j/messenger4j#81]
Hi All

My requirement is when user clicks on thumps up and thumps down, i need to capture those details as a feedback to the bot. PFA the screenshot.I tried subscribing for all messages in webhooks but still no message is coming from facebook when this is clicked.

![image](https://user-images.githubusercontent.com/36858559/37447707-4488968c-2849-11e8-95a4-c37c7f6ec894.png)

**Comment by maxgrabenhorst** [comment]
I will investigate if it is possible to handle this kind of action / event

**Comment by maxgrabenhorst** [comment]
Unfortunately there is no possibility so far to process this kind of action.
You could file a feature request directly on facebook.
I close this issue. Feel free to reopen if facebook messenger supports that feature.
