### ISSUE TITLE
Need help in handling a case where user needs to choose from a list of options 

### ISSUE THREAD

**Issue by nibinki** [messenger4j/messenger4j#82]
Hi,
I got a requirement where bot will provide a list of option to choose and user needs to provide his response. Eg , bot will ask user to choose from list of cities he like . Is there any option to provide a list of buttons and on click of button corresponding response needs to be sent to backend. I tried button template but only 3 button can be listed at 1 time also not finding any option to send the response back .

Please help

**Comment by maxgrabenhorst** [comment]
Please have a look at https://developers.facebook.com/docs/messenger-platform/send-messages
You could use Templates with Buttons or QuickReplies.
