### ISSUE TITLE
IllegalArgumentException when extracting json

### ISSUE THREAD

**Issue by uugan** [messenger4j/messenger4j#85]
Input json from FB:
`{"object":"page","entry":[{"id":"1","time":1524661955229,"messaging":[{"recipient":{"id":"1"},"timestamp":1524661955229,"sender":{"id":"2"},"postback":{"payload":"GET_STARTED_PAYLOAD","title":null}}]}]}`

```
messenger.onReceiveEvents(json, Optional.of(signature), event ->
                    {
                        processevent(event);
                    });

```
gives error like below:
```
java.lang.IllegalArgumentException
	at com.github.messenger4j.webhook.factory.PostbackEventFactory$$Lambda$1824/91086558.get(Unknown Source)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.github.messenger4j.webhook.factory.PostbackEventFactory.createEventFromJson(PostbackEventFactory.java:42)
	at com.github.messenger4j.webhook.factory.PostbackEventFactory.createEventFromJson(PostbackEventFactory.java:26)
	at com.github.messenger4j.webhook.factory.EventFactory.createEvent(EventFactory.java:42)
	at com.github.messenger4j.Messenger.onReceiveEvents(Messenger.java:150)
```

**Comment by maxgrabenhorst** [comment]
I will have a look, thanks for reporting.

**Comment by uugan** [comment]
Oh, I forgot to say. I'm using 1.0.0-M2.

**Comment by n0mer** [comment]
@uugan how do you calculate signature?

**Comment by uugan** [comment]
@n0mer 

SignatureUtil.java:

public static boolean isSignatureValid(String payload, String signature, String appSecret) {
        try {
            final Mac mac = Mac.getInstance(HMAC_SHA1);
            mac.init(new SecretKeySpec(appSecret.getBytes(), HMAC_SHA1));
            final byte[] rawHmac = mac.doFinal(payload.getBytes());

            final String expected = signature.substring(5);
            final String actual = bytesToHexString(rawHmac);

            return expected.equals(actual);
        } catch (NoSuchAlgorithmException | InvalidKeyException e) {
            throw new RuntimeException(e);
        }
    }

**Comment by n0mer** [comment]
@uugan thanks.

I'm getting the `signature` like this:

```java
final String signature = serverRequest.headers().header("X-Hub-Signature").get(0);
```

**Comment by uugan** [comment]
@n0mer 
Yes, I'm also getting signature like you do. I just use jax-rs. Sample:
`   @Path("/callback")
    @POST
    @Consumes("application/json")
    @Produces("application/atom+xml")
    public Response callback(@HeaderParam("X-Hub-Signature") final String signature, String json) {
                  messenger.onReceiveEvents(json, Optional.of(signature), event ->
                    {
                        handler.processEvent(event);
                    });
             return Response.status(200).build();
    }`
