### ISSUE TITLE
[q] is `appsecret_proof` supported

### ISSUE THREAD

**Issue by n0mer** [messenger4j/messenger4j#87]
## Generating the proof
The app secret proof is a sha256 hash of your access token, using the app secret as the key
https://developers.facebook.com/docs/graph-api/securing-requests

Did not found any mentions of `appsecret_proof` in source code, wondering whether is it supported?

**Comment by n0mer** [comment]
got this exception, maybe it is relevant:

```
om.github.messenger4j.exception.MessengerVerificationException: Signature verification failed. Provided signature does not match calculated signature.
	at com.github.messenger4j.Messenger.onReceiveEvents(Messenger.java:129)
```

**Comment by maxgrabenhorst** [comment]
Hi, the `appsecret_proof` is part of the Graph API and is not required / used for the Messenger Platform API.
To validate the signature just use your `App Secret`.
