### ISSUE TITLE
Gson refactoring

### ISSUE THREAD

**Issue by kord123** [messenger4j/messenger4j#9]
Hi, Max. I would like to make a pull request with some minor gson refactoring.
Particularly, this enhancement:

- Using FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES instead of explicit SerializedName annotations where possible

**Comment by maxgrabenhorst** [comment]
Hi Andriy,
sounds good to me.
Definitely an improvement 👍

**Comment by kord123** [comment]
#10

**Comment by maxgrabenhorst** [comment]
great contribution, thanks 👍
