### ISSUE TITLE
How to set message tag to NON_PROMOTIONAL_SUBSCRIPTION?

### ISSUE THREAD

**Issue by slvtn** [messenger4j/messenger4j#92]
Hello! 
Facebook updated their tags or smth like this, im confused.

I can not find NON_PROMOTIONAL_SUBSCRIPTION tag in this version of library.
Dear author tell me please what shoud i with my issue?

Also, thank you very much for your work, I really appreciate it.

**Comment by slvtn** [comment]
Oh, in your library NON_PROMOTIONAL_SUBSCRIPTION is not message tag, its message type. But it facebook docs its tag.
Im confused twice/

**Comment by maxgrabenhorst** [comment]
Facebook revised the semantics of messaging_type and message_tag. Will be updated in an upcoming version. Try to just use `NON_PROMOTIONAL_SUBSCRIPTION` as `messaging_type`.

**Comment by slvtn** [comment]
> Try to just use NON_PROMOTIONAL_SUBSCRIPTION as messaging_type.

It doens't work.
But when im sending message using rest request via CURL then the message is delivered successfully.
:(

2018-06-01 18:46:54.118  INFO  ***.MessengerService: FB MESSAGE REQUEST: MessagePayload(super=Payload(recipient=PhoneNumberRecipient(phoneNumber=*****, firstName=Optional.empty
, lastName=Optional.empty)), messagingType=NON_PROMOTIONAL_SUBSCRIPTION, message=TextMessage(super=Message(quickReplies=Optional.empty, metadata=Optional.empty), text=dssdsd), notificationType=Optional[REGULAR], tag=Optional.empty)
2018-06-01 18:46:54.442 ERROR ***.MessengerService: Error during sending to facebook!
com.github.messenger4j.exception.MessengerApiException: (#10) Requires phone matching access fee to be paid by this page unless the recipient user is an admin, developer, or tester of the app.

**Comment by maxgrabenhorst** [comment]
Fixed with messenger4j 1.0.0.
`NON_PROMOTIONAL_SUBSCRIPTION` is now a message tag instead of messaging type.
