### ISSUE TITLE
When is the next release ?

### ISSUE THREAD

**Issue by rasika-chandana** [messenger4j/messenger4j#94]
May I know when is the next release ? @maxgrabenhorst 

Appreciate if you can release as soon as possible since we need the  enum types "USER_EMAIL", "USER_PHONE_NUMBER" urgently. Thanks

**Comment by rasika-chandana** [comment]
@maxgrabenhorst

**Comment by maxgrabenhorst** [comment]
Hey Rasika,
we had a private conversation but I want to make the answer public:
Yesterday I released messenger4j 1.0.0 which includes the support for email and phone number quick replies.

Unfortunately at the same time I announced that the library is no longer maintained.
I love this project and would like to push it even further but I do not have enough time that I could spend on it. That makes me sad but I have to focus on other things.
I hope you understand this - sorry!

Best
Max

**Comment by bahadirkorumaz** [comment]
What does it mean? If it is not maintaned anymore should not I use it ?

**Comment by n0mer** [comment]
https://github.com/messenger4j/messenger4j/commit/a4d1251e4352ebc3bad3775c05a773d6a21c8d9c 'not maintained' status removed

**Comment by maxgrabenhorst** [comment]
I will release a new bugfix release soon. Feature releases will follow.

**Comment by izhidov** [comment]
Great! Thank you.

**Comment by maxgrabenhorst** [comment]
messenger4j 1.1.0 is out!
