### ISSUE TITLE
allow to override factories in com.github.messenger4j.webhook.factory.EventFactory#FACTORIES

### ISSUE THREAD

**Issue by n0mer** [messenger4j/messenger4j#97]
Hello @maxgrabenhorst , can you please allow us to supply custom factories in `com.github.messenger4j.webhook.factory.EventFactory#FACTORIES` ?

This will allow to supply custom processor for not-yet-implemented messages (for instance https://github.com/messenger4j/messenger4j/issues/95 - `template` attachments), and possible future API upgrades.

**Comment by PhantomYdn** [comment]
Supported in PR #99 . Please check example:
https://github.com/OrienteerBAP/messenger4j/blob/support-custom-events/src/test/java/com/github/messenger4j/test/integration/DocumentationTest.java#L252-L286

**Comment by maxgrabenhorst** [comment]
As commented in the linked PR, I would rather prefer to add missing features as fast as possible to m4j.

**Comment by n0mer** [comment]
@maxgrabenhorst so, are you going to support template attachments?

**Comment by maxgrabenhorst** [comment]
Yes :)
