### ISSUE TITLE
Ready to maintain your library

### ISSUE THREAD

**Issue by PhantomYdn** [messenger4j/messenger4j#98]
Hello, we are in https://github.com/OrienteerBAP using your library pretty deeply for chat-bots stuffs.
And yes - we are ready to maintain it for the community. If you are OK - will share our team members who will be involved into this activity.

**Comment by alexander-tampier** [comment]
that would be pretty awesome! So the community can keep contributing

**Comment by PhantomYdn** [comment]
@maxgrabenhorst , what do you think? We can for sure do work in a fork, but it's not bringing value to the community without merging back.

**Comment by maxgrabenhorst** [comment]
I'm in contact with Ilya to have a conversation if and how we can do it.

**Comment by sebastienfr** [comment]
Any news on the new maintainers ? We got more an more IllegalArgumentException out there and I guess it might come from some facebook API updates 😞

**Comment by n0mer** [comment]
@maxgrabenhorst can you please share some , hopefullly good, news ?

**Comment by n0mer** [comment]
@PhantomYdn Illia, nothing has been done ( according to https://github.com/OrienteerBAP/messenger4j/commits/master )

**Comment by maxgrabenhorst** [comment]
Good news guys 🎉 After being inactive for a while I'm now back and have the time to maintain it again. Thank you all for your patient. I really appreciate any contribution (please refer to contrib guidelines). In the next days I will an overview about what's changed lately and will start making messenger4j compatible to the current FB API version and will implementing new features.

**Comment by izhidov** [comment]
Thanks Max, good timing.
